//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAlertQueu
    {
        public int Id { get; set; }
        public int EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string EmailCc { get; set; }
        public string EmailBCc { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public int EmailSentStatu { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
        public string ErrorMessages { get; set; }
        public Nullable<int> AttachFileId { get; set; }
        public bool IsBodyHtml { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        public virtual File File { get; set; }
        public virtual User User { get; set; }
    }
}
