//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtensionViewer
    {
        public string Extension { get; set; }
        public Nullable<int> ViewerType { get; set; }
        public Nullable<int> RichDocumentFormat { get; set; }
        public Nullable<int> SpreatDocumentFormat { get; set; }
    }
}
