//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileProperty
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public int PropertyId { get; set; }
        public Nullable<bool> RequiredField { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual File File { get; set; }
        public virtual Property Property { get; set; }
    }
}
