//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.EmailAlertQueus = new HashSet<EmailAlertQueu>();
            this.FileAuditEvents = new HashSet<FileAuditEvent>();
            this.FileEmailAlertEvents = new HashSet<FileEmailAlertEvent>();
            this.FileEmailAlertSettings = new HashSet<FileEmailAlertSetting>();
            this.FileProperties = new HashSet<FileProperty>();
            this.FileVersions = new HashSet<FileVersion>();
            this.PublicFileAuditEvents = new HashSet<PublicFileAuditEvent>();
            this.ShareLinks = new HashSet<ShareLink>();
            this.TaskDocuments = new HashSet<TaskDocument>();
            this.Companies = new HashSet<Company>();
        }
    
        public int Id { get; set; }
        public int FolderId { get; set; }
        public int OwnerId { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public string Notes { get; set; }
        public Nullable<int> VersionCount { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> AuditId { get; set; }
        public Nullable<bool> AuditInherit { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> FlagId { get; set; }
        public int CompanyId { get; set; }
        public int CategoryId { get; set; }
        public int TypeId { get; set; }
        public string DocNumber { get; set; }
        public Nullable<int> ActiveVersionId { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int FileType { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string FileSource { get; set; }
        public string VersionNumberforExternal { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    
        public virtual AuditTemplate AuditTemplate { get; set; }
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual DocsType DocsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAlertQueu> EmailAlertQueus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileAuditEvent> FileAuditEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileEmailAlertEvent> FileEmailAlertEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileEmailAlertSetting> FileEmailAlertSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileProperty> FileProperties { get; set; }
        public virtual Flag Flag { get; set; }
        public virtual FolderStructure FolderStructure { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileVersion> FileVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicFileAuditEvent> PublicFileAuditEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareLink> ShareLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDocument> TaskDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
    }
}
