//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileVersion()
        {
            this.FileAuditEvents = new HashSet<FileAuditEvent>();
            this.PublicFileAuditEvents = new HashSet<PublicFileAuditEvent>();
        }
    
        public int Id { get; set; }
        public int FileId { get; set; }
        public int FileSize { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int UserId { get; set; }
        public int Version { get; set; }
        public string VersionNote { get; set; }
        public Nullable<int> FlagId { get; set; }
        public string Extension { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string Sha1 { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string RevNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileAuditEvent> FileAuditEvents { get; set; }
        public virtual File File { get; set; }
        public virtual FileVersionData FileVersionData { get; set; }
        public virtual Flag Flag { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicFileAuditEvent> PublicFileAuditEvents { get; set; }
    }
}
