//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FolderStructure()
        {
            this.Files = new HashSet<File>();
            this.FolderAuditEvents = new HashSet<FolderAuditEvent>();
            this.FolderEmailAlertEvents = new HashSet<FolderEmailAlertEvent>();
            this.FolderEmailAlertSettings = new HashSet<FolderEmailAlertSetting>();
            this.FolderGroupSecurityTemplates = new HashSet<FolderGroupSecurityTemplate>();
            this.FolderProperties = new HashSet<FolderProperty>();
            this.FolderStructures1 = new HashSet<FolderStructure>();
            this.Sections = new HashSet<Section>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FullParentAddress { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool DeleteFlag { get; set; }
        public string Desc { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int OwnerId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<int> SectionId { get; set; }
        public bool HasChild { get; set; }
        public Nullable<int> AuditId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> IconId { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> AuditInherit { get; set; }
        public Nullable<int> Flag_Id { get; set; }
    
        public virtual AuditTemplate AuditTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Flag Flag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolderAuditEvent> FolderAuditEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolderEmailAlertEvent> FolderEmailAlertEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolderEmailAlertSetting> FolderEmailAlertSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolderGroupSecurityTemplate> FolderGroupSecurityTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolderProperty> FolderProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolderStructure> FolderStructures1 { get; set; }
        public virtual FolderStructure FolderStructure1 { get; set; }
        public virtual Icon Icon { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}
