//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicFileAuditEvent
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> FileId { get; set; }
        public Nullable<int> FileVersionId { get; set; }
        public System.DateTime EventTime { get; set; }
        public int Event { get; set; }
        public string Message { get; set; }
        public bool Access { get; set; }
    
        public virtual File File { get; set; }
        public virtual FileVersion FileVersion { get; set; }
    }
}
