//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerSetting
    {
        public string TagName { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public bool EditOnList { get; set; }
        public int DataType { get; set; }
    }
}
