//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareLink
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public int UserId { get; set; }
        public bool SetPassword { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string MailAddress { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Guid { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> AprrovedById { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    
        public virtual File File { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
