//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskRouting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskRouting()
        {
            this.TaskDocuments = new HashSet<TaskDocument>();
            this.TaskNotes = new HashSet<TaskNote>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool Importand { get; set; }
        public int OwnerId { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public Nullable<bool> EmailAlertFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDocument> TaskDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNote> TaskNotes { get; set; }
        public virtual TaskStatue TaskStatue { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
