//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNote
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public string Note { get; set; }
        public System.DateTime DateTime { get; set; }
        public int UserId { get; set; }
    
        public virtual TaskRouting TaskRouting { get; set; }
        public virtual User User { get; set; }
    }
}
