//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvCSharp.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDocument
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int FileId { get; set; }
    
        public virtual File File { get; set; }
        public virtual TaskRouting TaskRouting { get; set; }
    }
}
